config/routes.rb
Rails.application.routes.draw do

  resources :trips
  resources :boats
  resources :guides

  get 'events/calendar', to: 'events/calendar#show', as: 'events_calendar'

  resources :events do
    resources :bookings, module: :events
    resource :logbook, module: :events
  end

  resources :customers do
    resource :logbook, module: :customers
    resources :bookings, module: :customers
    resources :rentals, module: :customers do
      post :return, on: :member
    end
  end

  namespace :equipment do
    resources :categories
  end

  resources :equipment

  namespace :autocomplete do
    resources :customers,      only: [:index, :show]
    resources :trips,          only: [:index, :show]
    resources :boats,          only: [:index, :show]
    resources :events,         only: [:index, :show]
    resources :certifications, only: :index
  end

  resources :statistics, only: [:index]

  root 'home#index'

end

app/models/boat.rb
class Boat < ActiveRecord::Base

  scope :alphabetical, -> { order :name }
  scope :search, ->(query) { where { (code =~ ('%s%' % query)) | (name =~ ('%s%' % query))} }

  validates :code, presence: true, length: { maximum: 3 }, uniqueness: true
  validates :name, presence: true
  validates :capacity, numericality: { greater_than: 0, allow_nil: true }

end

app/controllers/autocomplete/boats_controller.rb
module Autocomplete
  class BoatsController < ApplicationController

    expose(:boats) do
      boats = Boat.alphabetical
      boats = boats.search(params[:q]) if params[:q].present?
      boats.limit(10)
    end

    expose(:boat)

  end
end

app/controllers/boats_controller.rb
class BoatsController < ApplicationController

  active_navbar_item :admin

  expose(:boats) { Boat.alphabetical }
  expose(:boat, attributes: :boat_params)

  def create
    if boat.save
      redirect_to :boats, notice: 'Boat was successfully created.'
    else
      render :new
    end
  end

  def update
    if boat.save
      redirect_to :boats, notice: 'Boat was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    boat.destroy
    redirect_to :boats, notice: 'Boat was successfully deleted.'
  end

  private

  def boat_params
    params.require(:boat).permit(:code, :name, :capacity)
  end
end

app/views/boats/_form.html.haml
= simple_form_for(boat) do |f|
  = f.error_notification

  .form-inputs
    .row
      .col-sm-2
        = f.input :code, maxlength: true
      .col-sm-2
        = f.input :capacity, as: :numeric
      .col-sm-8
        = f.input :name

  .form-actions
    = f.button :submit, class: 'btn btn-primary'
    = link_to t(:back), :back, class: 'btn btn-default'

app/views/boats/_row.html.haml
%tr[boat]
  %td.label-column
    - if boat.code.present?
      .label.label-primary<
        = boat.code
  %td.col-sm-3.col-xs-4
    = link_to edit_boat_path(boat) do
      = boat.name
  %td.text-muted
    - if boat.capacity.present?
      %i.fa.fa-user
      &times;
      = boat.capacity
  %td.actions-column
    = action_links_for boat, :delete

app/views/boats/_table.html.haml
%table.table.table-striped
  %thead
    %tr
      %th
      %th Name
      %th Capacity
      %th
  %tbody
    = render partial: 'row', collection: boats, as: :boat

app/views/boats/edit.html.haml
- page_header boat.name, icon: 'anchor', subtitle: icon(:pencil, t('.subtitle')) do
  = link_to icon(:list, t('boats.common.list_boats')), boats_path, class: 'btn btn-default'

.box
  .box-body
    = render 'form'

app/views/boats/index.html.haml
- page_header t('.title'), icon: 'anchor' do
  = link_to new_boat_path, class: 'btn btn-success' do
    = icon 'plus-circle', t('.add_boat')

.box
  .box-body.no-padding
    = render 'table'

app/views/boats/new.html.haml
- page_header t('.title'), icon: 'anchor' do
  = link_to icon(:list, t('boats.common.list_boats')), boats_path, class: 'btn btn-default'

.box
  .box-body
    = render 'form'